---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: home-homelab
spec:
  addresses:
    - 192.168.4.200-192.168.4.254
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
spec:
  ipAddressPools:
    - home-homelab
