---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 1h
  target:
    name: cloudflare-token
    template:
      data:
        token: "{{ .token }}"
  dataFrom:
    - extract:
        key: cloudflare
        decodingStrategy: Base64
