---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless-ngx
  namespace: flux-system
spec:
  targetNamespace: paperless-ngx
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: cloudnative-pg
  path: ./kubernetes/apps/paperless-ngx/paperless-ngx/app
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
