---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
spec:
  interval: 10m
  chart:
    spec:
      chart: connect
      version: 1.16.0
      sourceRef:
        kind: HelmRepository
        name: onepassword-connect
        namespace: external-secrets
  values:
    connect:
      credentialsName: onepassword-connect-secrets
      credentialsKey: 1password-credentials.json
