---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-controller
  namespace: default
spec:
  interval: 10m
  wait: true
  timeout: 5m
  retryInterval: 1m
  prune: true
  targetNamespace: external-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infrastructure/external-secrets/external-secrets/controller
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-stores
  namespace: default
spec:
  interval: 30m
  wait: true
  timeout: 5m
  retryInterval: 1m
  prune: true
  targetNamespace: external-secrets
  dependsOn:
    - name: external-secrets-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./infrastructure/external-secrets/external-secrets/stores
