---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  targetNamespace: external-secrets
  dependsOn:
    - name: onepassword-connect
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/infrastructure/external-secrets/external-secrets/controller
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-stores
  namespace: flux-system
spec:
  targetNamespace: external-secrets
  dependsOn:
    - name: external-secrets
    - name: onepassword-connect
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/infrastructure/external-secrets/external-secrets/stores
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
