---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: datadog
  namespace: flux-system
spec:
  targetNamespace: datadog
  dependsOn:
    - name: external-secrets-stores
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/infrastructure/datadog/datadog/controller
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
