---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: datadog
spec:
  interval: 10m
  chart:
    spec:
      chart: datadog
      version: 3.72.1
      sourceRef:
        kind: HelmRepository
        name: datadog
        namespace: datadog
  values:
    datadog:
      apiKeyExistingSecret: datadog-api-key
      clusterName: home
      logs:
        enabled: true
        containerCollectAll: true
      processAgent:
        enabled: true
        processCollection: true
