---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
spec:
  interval: 10m
  chart:
    spec:
      chart: renovate
      version: 38.93.1
      sourceRef:
        kind: HelmRepository
        name: renovate
        namespace: renovate
  values:
    secrets: github-pat
    renovate:
      config: |-
        {
          "extends": ["config:recommended"],
          "platform": "github",
          "repositories": ["lazyIoad/lazylab"]
        }
