---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-scripts-config
data:
  init.sh: |
    #!/bin/sh
    echo "Running init container"
    mkdir -p /data/public /data/private
    # Change directories to syncthing user (which is called "abc")
    chown -R 911:1000 /data/public /data/private
    echo "Init container done"
