---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80 default_server;

        root /data;
        index index.html;

        server_name localhost;

        location / {
                autoindex on;
                try_files $uri $uri/ =404;
        }

        location /private {
                autoindex on;
                auth_basic "Private Area";
                auth_basic_user_file /etc/nginx/secret/htpasswd;
                try_files $uri $uri/ =404;
        }
    }
