---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      version: 0.17.0
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets
