---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: onepassword-connect
  namespace: default
spec:
  interval: 10m
  wait: true
  timeout: 5m
  retryInterval: 1m
  prune: true
  targetNamespace: external-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/external-secrets/onepassword-connect/controller
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
