---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: multus
  namespace: flux-system
spec:
  targetNamespace: multus
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/infrastructure/multus/multus/controller
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: multus-config
  namespace: flux-system
spec:
  targetNamespace: multus
  dependsOn:
    - name: multus
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/infrastructure/multus/multus/config
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
