---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 10m
  chart:
    spec:
      chart: longhorn
      version: 1.7.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
  values:
    persistence:
      defaultClassReplicaCount: 2
      defaultFsType: xfs
      reclaimPolicy: Retain
      defaultDataLocality: best-effort
    defaultSettings:
      defaultReplicaCount: 2
      defaultDataLocality: best-effort
      createDefaultDiskLabeledNodes: true
      defaultDataPath: "/data/longhorn/"
      storageMinimalAvailablePercentage: 10
      storageReservedPercentageForDefaultDisk: 0
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        external-dns.alpha.kubernetes.io/hostname: longhorn.lazylab.casa
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: ui-auth
      host: longhorn.lazylab.casa
      tls: true
      tlsSecret: longhorn-tls
