---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
spec:
  interval: 10m
  chart:
    spec:
      chart: podinfo
      version: "6.7.0"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: podinfo
  values:
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-staging
        external-dns.alpha.kubernetes.io/hostname: podinfo.lazylab.casa
      hosts:
        - host: podinfo.lazylab.casa
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - podinfo.lazylab.casa
          secretName: podinfo-tls
