---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: cloudflared
  template:
    metadata:
      creationTimestamp: null
      labels:
        pod: cloudflared
    spec:
      containers:
        - command:
            - cloudflared
            - tunnel
            - --no-autoupdate
            - run
          args:
            - --token
            - "$(TOKEN)"
            - --loglevel
            - debug
          image: cloudflare/cloudflared:2024.9.1
          name: cloudflared
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: tunnel-token
                  key: token
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
        - command: ["sleep", "3600"]
          image: alpine:latest
          name: debug
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: tunnel-token
                  key: token
