---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: cloudflared
  template:
    metadata:
      creationTimestamp: null
      labels:
        pod: cloudflared
    spec:
      containers:
        - command:
            - cloudflared
            - tunnel
            - --no-autoupdate
            - run
          args:
            - --token
            - "$(TOKEN)"
          image: cloudflare/cloudflared:2024.11.0
          name: cloudflared
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: tunnel-token
                  key: token
