---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: cloudflared
  template:
    spec:
      containers:
        - command:
            - cloudflared
            - tunnel
            - --no-autoupdate
            - run
          args:
            - --token
            - $TOKEN
          image: cloudflare/cloudflared:latest
          name: cloudflared
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: tunnel-token
                  key: token
          livenessProbe:
            httpGet:
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
