---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  targetNamespace: podinfo
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/apps/podinfo/podinfo/app
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
