---
apiVersion: external-secrets.io/v1
# TODO: secure this
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
  namespace: external-secrets
spec:
  provider:
    onepasswordSDK:
      vault: Lazylab
      auth:
        serviceAccountSecretRef:
          name: onepassword-connect-secrets
          key: token
  conditions:
    - namespaces: []
