---
apiVersion: external-secrets.io/v1
# TODO: secure this
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
spec:
  provider:
    onepasswordSDK:
      vaults: Lazylab
      auth:
        serviceAccountSecretRef:
          name: onepassword-connect-secrets
          key: token
