---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
spec:
  instances: 1
  storage:
    size: 8Gi
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.4
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
    enableAlterSystem: true
  bootstrap:
    initdb:
      postInitApplicationSQL:
        - ALTER SYSTEM SET search_path TO "$user", public, vectors;
        - SET search_path TO "$user", public, vectors;
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS "cube";
        - CREATE EXTENSION IF NOT EXISTS "earthdistance";
        - ALTER SCHEMA vectors OWNER TO "app";
        - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA vectors TO "app";
        - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "app";
