---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-data
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500G
