---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 10m
  chart:
    spec:
      chart: immich
      version: 0.8.1
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: flux-system
  values:
    env:
      - name: REDIS_HOSTNAME
        value: immich-redis.immich.svc.cluster.local
      - name: DB_HOSTNAME
        value: immich-db-rw.immich.svc.cluster.local
      - name: DB_USERNAME
        valueFrom:
          secretKeyRef:
            name: immich-db-app
            key: user
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: immich-db-app
            key: password
      - name: DB_DATABASE_NAME
        valueFrom:
          secretKeyRef:
            name: immich-db-app
            key: dbname
      - name: IMMICH_MACHINE_LEARNING_URL
        value: http://immich-machine-learning:3003

    immich:
      persistence:
        library:
          size: 500Gi
          accessMode: ReadWriteOnce

    machine-learning:
      enabled: true
      persistence:
        cache:
          type: pvc
          accessMode: ReadWriteOnce
          storageClass: longhorn

    server:
      ingress:
        main:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-production
            external-dns.alpha.kubernetes.io/hostname: photos.lazylab.casa
          hosts:
            - host: photos.lazylab.casa
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - photos.lazylab.casa
              secretName: immich-tls
