---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 10m
  chart:
    spec:
      chart: immich
      version: 0.8.1
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: immich
  values:
    env:
      - name: REDIS_HOSTNAME
        value: immich-redis-master
      - name: DB_HOSTNAME
        value: immich-postgresql
      - name: DB_USERNAME
        value: immich
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-password
            key: password
      - name: DB_DATABASE_NAME
        value: immich
      - name: IMMICH_MACHINE_LEARNING_URL
        value: http://immich-machine-learning:3003

    immich:
      persistence:
        library:
          existingClaim: immich-data

    machine-learning:
      enabled: true
      persistence:
        cache:
          type: pvc
          accessMode: ReadWriteOnce
          storageClass: longhorn

    postgresql:
      enabled: true
      global:
        postgresql:
          auth:
            existingSecret: postgres-password
      primary:
        resourcesPreset: none

    redis:
      enabled: true
      global:
        redis:
      master:
        resourcesPreset: none

    server:
      service:
        main:
          enabled: true
          type: LoadBalancer
          loadBalancerClass: tailscale
      ingress:
        main:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-production
            external-dns.alpha.kubernetes.io/hostname: photos.lazylab.casa
          hosts:
            - host: photos.lazylab.casa
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - photos.lazylab.casa
              secretName: immich-tls
