---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/playbook
- name: Set up storage config
  become: true
  hosts: storage
  tasks:
    - name: Make config directory
      ansible.builtin.file:
        path: "/etc/rancher/k3s/config.yaml.d"
        mode: "0755"
        state: directory
    - name: Create storage config
      ansible.builtin.copy:
        dest: "/etc/rancher/k3s/config.yaml.d/storage-labels.yaml"
        mode: "0644"
        content: |
          ---
          node-label:
            - storage=longhorn
            - node.longhorn.io/create-default-disk=true

- name: Add quadratus-3 node taint
  become: true
  hosts: quadratus-3
  tasks:
    - name: Make config directory
      ansible.builtin.file:
        path: "/etc/rancher/k3s/config.yaml.d"
        mode: "0755"
        state: directory
    - name: Create storage config
      ansible.builtin.copy:
        dest: "/etc/rancher/k3s/config.yaml.d/storage-taints.yaml"
        mode: "0644"
        content: |
          ---
          node-taint:
            - "slow-storage=true:NoSchedule"

- name: Set up quadratus-2
  become: true
  hosts: quadratus-2
  tasks:
    - name: Make k3s config directory
      ansible.builtin.file:
        path: "/etc/rancher/k3s/config.yaml.d"
        mode: "0755"
        state: directory
    - name: Create usb label
      ansible.builtin.copy:
        dest: "/etc/rancher/k3s/config.yaml.d/usb-labels.yaml"
        mode: "0644"
        content: |
          ---
          node-label:
            - "usb=skyconnect"
    - name: Create ser2net config
      ansible.builtin.copy:
        dest: "/etc/ser2net.yaml"
        mode: "0644"
        content: |
          connection: &zigbee
            accepter: ipv4,tcp,3333
            enable: on
            connector: serialdev,/dev/ttyUSB0,57600n81,local,nobreak
            options:
              kickolduser: true
    - name: Install ser2net
      ansible.builtin.apt:
        pkg:
          - ser2net

- name: Install k3s
  ansible.builtin.import_playbook: k3s.orchestration.site
  vars:
    ansible_port: 22
    token: "{{ lookup('env', 'K3S_TOKEN') }}"
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
    extra_server_args: "--disable servicelb --disable traefik --disable local-storage"
    extra_agent_args: ""
    kubeconfig: ~/.kube/config
    cluster_context: lazylab
