---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/playbook
- name: Update system
  become: true
  hosts: all
  tasks:
    - name: Perform an apt-upgrade
      ansible.builtin.apt:
        upgrade: full
        update_cache: true
        autoclean: true
        autoremove: true

    - name: Check if a reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_checksum: false
      register: reboot_required_file

    - name: Reboot the server if required
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists

- name: Update k3s
  ansible.builtin.import_playbook: k3s.orchestration.upgrade
