---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 10m
  chart:
    spec:
      chart: cert-manager
      version: v1.16.1
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
  values:
    crds:
      enabled: true
    clusterResourceNamespace: cert-manager
