---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
- name: Perform an apt-upgrade
  ansible.builtin.apt:
    upgrade: full
    update_cache: true

- name: Install other dependencies
  ansible.builtin.apt:
    pkg:
      - open-iscsi
      - nfs-common
      - cryptsetup
      - dmsetup

- name: Reboot hosts
  throttle: 1
  ansible.builtin.reboot:

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true
