---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
- name: Perform an apt-upgrade
  ansible.builtin.apt:
    upgrade: full
    update_cache: true

- name: Install other dependencies
  ansible.builtin.apt:
    pkg:
      - open-iscsi
      - nfs-common
      - cryptsetup
      - dmsetup
      - chrony

# See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes
- name: Set net.core.rmem_max
  ansible.posix.sysctl:
    name: net.core.rmem_max
    value: "7500000"
    state: present

# See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes
- name: Set net.core.wmem_max
  ansible.posix.sysctl:
    name: net.core.wmem_max
    value: "7500000"
    state: present

- name: Reboot hosts
  throttle: 1
  ansible.builtin.reboot:

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true
