---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/ansible.json#/$defs/tasks
- name: Perform an apt-upgrade
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true

- name: Install other dependencies
  ansible.builtin.apt:
    pkg:
      - chrony
      - rsync

# See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes
- name: Set net.core.rmem_max
  ansible.posix.sysctl:
    name: net.core.rmem_max
    value: "7500000"
    state: present

# See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes
- name: Set net.core.wmem_max
  ansible.posix.sysctl:
    name: net.core.wmem_max
    value: "7500000"
    state: present

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists

- name: Remove dependencies that are no longer required
  ansible.builtin.apt:
    autoremove: true
