---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: onepassword-connect
  namespace: flux-system
spec:
  targetNamespace: external-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/infrastructure/external-secrets/onepassword-connect/controller
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
