---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: cloudflare-token
spec:
  externalSecretName: cloudflare-token
  namespaceSelectors:
    - matchLabels:
      "kubernetes.io/metadata.name": kube-system
  refreshTime: 1m
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: onepassword-connect
    refreshInterval: 1h
    target:
      name: cloudflare-token
      template:
        data:
          token: "{{ .token }}"
    dataFrom:
      - extract:
          key: cloudflare
          decodingStrategy: Base64
