---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
spec:
  selector:
    matchLabels:
      app: home-assistant
  replicas: 1
  template:
    metadata:
      labels:
        app: home-assistant
      annotations:
        k8s.v1.cni.cncf.io/networks: multus/macvlan-homelab
    spec:
      terminationGracePeriodSeconds: 60
      initContainers:
        - name: create-config
          image: registry.hub.docker.com/library/busybox:1.36.1
          command: ["sh", "/scripts/config.sh"]
          volumeMounts:
            - name: config
              mountPath: /config
            - name: scripts
              mountPath: /scripts/
      containers:
        - name: home-assistant
          image: ghcr.io/home-assistant/home-assistant:2024.10.0
          command:
            - sh
          args:
            - "-c"
            # - "/scripts/zigbee.sh && python -m homeassistant --config /config"
            - "python -m homeassistant --config /config"
          ports:
            - name: server
              containerPort: 8123
          volumeMounts:
            - name: config
              mountPath: /config
            - name: scripts
              mountPath: /scripts/
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: home-assistant-config
        - name: scripts
          configMap:
            name: scripts-config
            defaultMode: 0555
      nodeSelector:
        usb: skyconnect
