---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: google-service-account
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 1h
  dataFrom:
    - extract:
        key: home-assistant-google-svc-act
        property: SERVICE_ACCOUNT.JSON
