---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-config
data:
  zigbee.sh: |
    #!/bin/sh
    socat pty,link=/dev/ttyUSB0,raw,user=0,group=0,mode=777 tcp:127.0.0.1:3333 &
  config.sh: |
    #!/bin/bash
    set -e

    # Check if the configuration file exists
    if [ ! -f /config/configuration.yaml ]; then
      echo "Configuration file not found, creating a new one"
      cat <<- EOF > /config/configuration.yaml
      default_config:
        http:
          use_x_forwarded_for: true
          trusted_proxies:
            - 10.0.0.0/8
    EOF
    fi
