---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  targetNamespace: metallb-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/infrastructure/metallb-system/metallb/controller
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  targetNamespace: metallb-system
  dependsOn:
    - name: metallb
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/infrastructure/metallb-system/metallb/config
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
