---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate
spec:
  interval: 10m
  chart:
    spec:
      chart: renovate
      version: 38.93.1
      sourceRef:
        kind: HelmRepository
        name: renovate
        namespace: renovate
  values:
    existingSecret: github-pat
    cronjob:
      ttlSecondsAfterFinished: 1h
    renovate:
      config: |-
        {
          "extends": [
            ":dependencyDashboard",
            ":semanticPrefixFixDepsChoreOthers",
            "group:monorepos",
            "group:recommended",
            "replacements:all",
            "workarounds:all"
          ],
          "platform": "github",
          "repositories": ["lazyIoad/lazylab"],
          "ignorePaths": ["ansible/ansible_collections/**", "ansible/roles/**"],
          "customDatasources": {
            "k3s": {
              "defaultRegistryUrlTemplate": "https://update.k3s.io/v1-release/channels",
              "transformTemplates": [
                "{\"releases\":[{\"version\": $$.(data[id = 'stable'].latest),\"sourceUrl\":\"https://github.com/k3s-io/k3s\",\"changelogUrl\":$join([\"https://github.com/k3s-io/k3s/releases/tag/\",data[id = 'stable'].latest])}],\"sourceUrl\": \"https://github.com/k3s-io/k3s\",\"homepage\": \"https://k3s.io/\"}"
              ]
            }
          },
          "kubernetes": {
            "fileMatch": ["^kubernetes/.+\\.yaml$"]
          }
        }
