---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: system-upgrade-controller
spec:
  interval: 10m
  chart:
    spec:
      chart: nimbolus
      version: 0.4.1
      sourceRef:
        kind: HelmRepository
        name: nimbolus
        namespace: system-upgrade-controller
