---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 1h
  target:
    name: paperless-secrets
    template:
      data:
        secret-key: "{{ .secretkey }}"
        admin-user: "{{ .adminuser }}"
        admin-password: "{{ .adminpw }}"
  dataFrom:
    - extract:
        key: paperless-ngx
        decodingStrategy: None
