---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo-redis
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      redis:
        containers:
          app:
            image:
              repository: registry.redict.io/redict
              tag: 7.3.1

    service:
      redis:
        controller: redis
        ports:
          http:
            port: 6379
