---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 1h
  target:
    name: operator-oauth
    template:
      data:
        client_id: "{{ .id }}"
        client_secret: "{{ .secret }}"
  dataFrom:
    - extract:
        key: tailscale-operator-oauth
        decodingStrategy: None
