---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
spec:
  interval: 10m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.74.1
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
