---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
  namespace: external-secrets
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.external-secrets.svc.cluster.local:8080
      vaults:
        Lazylab: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-secrets
            key: token
            namespace: external-secrets
